USE [master]
GO

/****** Object:  Database [ShopLapDB]    Script Date: 23/03/2023 10:24:16 CH ******/
CREATE DATABASE [ShopLapDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopLapDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopLapDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShopLapDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopLapDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopLapDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShopLapDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShopLapDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShopLapDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShopLapDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShopLapDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShopLapDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ShopLapDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShopLapDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShopLapDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShopLapDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShopLapDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShopLapDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShopLapDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShopLapDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShopLapDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ShopLapDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShopLapDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShopLapDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShopLapDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShopLapDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShopLapDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ShopLapDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShopLapDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShopLapDB] SET  MULTI_USER 
GO

ALTER DATABASE [ShopLapDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShopLapDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShopLapDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShopLapDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShopLapDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShopLapDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShopLapDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ShopLapDB] SET  READ_WRITE 
GO

